Repository fzxiao233/matsuri.design, pull requests merged in 2019-11, with the labels that each got.

#6 扁平化前端界面，少量文案修改
  src/components/CommentArea.vue
  src/components/CommentForm.vue
  src/components/Jumbotron.vue
  src/components/NavMenu.vue
  src/components/QueueForm.vue
  src/components/VideoList.vue
  src/views/Home.vue
Labels: bug, dependencies

#7 添加m3u8支持
  README.md
  package.json
  public/AZRSfPJkeO6Ucj4.jpg
  src/components/FlvPlayer.vue
  src/components/VideoList.vue
  src/components/VideoPlayer.vue
  src/views/Home.vue
  yarn.lock
Labels: enhancement

#8 Add/m3u8
  package.json
  src/components/VideoPlayer.vue
  src/http-streaming/CHANGELOG.md
  src/http-streaming/LICENSE
  src/http-streaming/README.md
  src/http-streaming/dist/videojs-http-streaming.cjs.js
  src/http-streaming/dist/videojs-http-streaming.es.js
  src/http-streaming/dist/videojs-http-streaming.js
  src/http-streaming/dist/videojs-http-streaming.min.js
  src/http-streaming/package.json
  yarn.lock
Labels: bug, enhancement

#9 修复在原生hls平台上无法播放的问题
  src/components/VideoPlayer.vue
Labels: bug
